name: DCM Deploy (my_test)

on:
  push:
    branches: ["main"]
    paths:
      - 'manifest.yml'
      - 'definitions/**'

permissions:
  contents: read
  pull-requests: write

env:
  SNOWFLAKE_USER: GH_ACTIONS_SVC_USER
  SNOWFLAKE_PASSWORD: ${{ secrets.DEPLOYER_PAT }}
  SNOWFLAKE_AUTHENTICATOR: PROGRAMMATIC_ACCESS_TOKEN

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: DCM_TEST
    steps:
      - uses: actions/checkout@v4

      - uses: snowflakedb/snowflake-actions@v3
        with:
          use-oidc: "false"

      - name: DCM Plan
        run: snow dcm plan --target DCM_TEST -x

      - name: DCM Deploy
        run: snow dcm deploy --target DCM_TEST -x
