name: DCM Plan (PR Preview)

on:
  pull_request:
    branches: ["main"]
    paths:
      - 'manifest.yml'
      - 'definitions/**'

permissions:
  contents: read
  pull-requests: write

env:
  SNOWFLAKE_USER: GH_ACTIONS_SVC_USER
  SNOWFLAKE_PASSWORD: ${{ secrets.DEPLOYER_PAT }}
  SNOWFLAKE_AUTHENTICATOR: PROGRAMMATIC_ACCESS_TOKEN

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: DCM_TEST
    steps:
      - uses: actions/checkout@v4

      - uses: snowflakedb/snowflake-actions@v3
        with:
          use-oidc: "false"

      - name: DCM Plan
        run: snow dcm plan --target DCM_TEST -x
